# Generated by Django 3.2.7 on 2021-10-22 16:47

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MKBRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mkb_code', models.CharField(max_length=10, unique=True)),
                ('title', models.TextField()),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('contents', models.TextField(blank=True, null=True)),
                ('actual', models.BooleanField(default=True)),
                ('act_date', models.DateField(blank=True, null=True)),
                ('parent', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'MKBRecord',
                'managed': True,
            },
            managers=[
                ('records', django.db.models.manager.Manager()),
            ],
        ),
    ]
