# Generated by Django 3.2.7 on 2021-11-24 16:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mkb', '0002_alphabet_alphabetcategory_alphabetgroup'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='alphabetcategory',
            managers=[
                ('categories', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='alphabetgroup',
            managers=[
                ('groups', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='mkbrecord',
            name='sign',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
