# Generated by Django 3.2.7 on 2022-01-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkb', '0004_remove_mkbrecord_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='alphabetgroup',
            name='is_static',
            field=models.BooleanField(default=False),
        ),
    ]
