# Generated by Django 3.2.7 on 2022-01-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkb', '0005_alphabetgroup_is_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='alphabetgroup',
            name='f_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
