# Generated by Django 3.2.7 on 2022-01-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkb', '0006_alphabetgroup_f_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alphabetgroup',
            old_name='f_name',
            new_name='component',
        ),
    ]
