# Generated by Django 3.2.7 on 2022-01-31 11:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mkb', '0007_rename_f_name_alphabetgroup_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alphabetgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Chemicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code_1', models.CharField(max_length=6)),
                ('code_2', models.CharField(max_length=6)),
                ('code_3', models.CharField(max_length=6)),
                ('code_4', models.CharField(max_length=6)),
                ('code_5', models.CharField(max_length=6)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mkb.alphabetgroup')),
            ],
            options={
                'db_table': 'Chemicals',
                'managed': True,
            },
            managers=[
                ('chemicals', django.db.models.manager.Manager()),
            ],
        ),
    ]
