# Generated by Django 3.2.7 on 2022-01-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkb', '0008_auto_20220131_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alphabetgroup',
            name='component',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
