# Generated by Django 3.2.7 on 2022-01-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkb', '0009_alter_alphabetgroup_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicals',
            name='code_1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='chemicals',
            name='code_2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='chemicals',
            name='code_3',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='chemicals',
            name='code_4',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='chemicals',
            name='code_5',
            field=models.CharField(max_length=10),
        ),
    ]
